!SESSION 2015-03-22 22:45:04.213 -----------------------------------------------
eclipse.buildId=4.3.0.M20130911-1000
java.version=1.7.0_51
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.standard.product -product org.eclipse.epp.package.standard.product -keyring /Users/mac/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.standard.product -data /Users/mac/Documents/workspace/Project -product org.eclipse.epp.package.standard.product -keyring /Users/mac/.eclipse_keyring -showlocation

This is a continuation of log file /Users/mac/Documents/workspace/Project/.metadata/.bak_0.log
Created Time: 2015-03-22 22:45:06.745
!SESSION 2015-03-22 22:45:04.213 -----------------------------------------------
eclipse.buildId=4.3.0.M20130911-1000
java.version=1.7.0_51
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.standard.product -product org.eclipse.epp.package.standard.product -keyring /Users/mac/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.standard.product -data /Users/mac/Documents/workspace/Project -product org.eclipse.epp.package.standard.product -keyring /Users/mac/.eclipse_keyring -showlocation

!ENTRY org.eclipse.core.resources 2 10035 2015-03-22 22:45:06.745
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

!ENTRY org.eclipse.core.net 1 0 2015-03-22 22:45:07.207
!MESSAGE System property http.nonProxyHosts has been set to local|*.local|169.254/16|*.169.254/16 by an external source. This value will be overwritten using the values from the preferences

!ENTRY org.eclipse.jface 2 0 2015-03-22 22:45:14.916
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2015-03-22 22:45:14.916
!MESSAGE A conflict occurred for ALT+COMMAND+R:
Binding(ALT+COMMAND+R,
	ParameterizedCommand(Command(org.python.pydev.debug.setnext,Set Next Statement,
		,
		Category(org.python.pydev.ui.category.run,PyDev - Run,Python run category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@45b5c406,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(ALT+COMMAND+R,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.edit.text.java.rename.element,Rename - Refactoring ,
		Rename the selected element,
		Category(org.eclipse.jdt.ui.category.refactoring,Refactor - Java,Java Refactoring Actions,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@14b64a24,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,cocoa,system)

!ENTRY org.python.pydev.shared_core 4 4 2015-03-22 22:45:46.106
!MESSAGE java.io.IOException: Cannot run program "/usr/local/bin/python3.4": error=2, No such file or directory
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "/usr/local/bin/python3.4": error=2, No such file or directory
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:308)
	at org.python.pydev.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:325)
	at org.python.pydev.runners.SimplePythonRunner.runAndGetOutputWithInterpreter(SimplePythonRunner.java:95)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:68)
	at org.python.pydev.ui.interpreters.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:44)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:381)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager$CreateInterpreterInfoCallback.createInterpreterInfo(SynchSystemModulesManager.java:173)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.updateStructures(SynchSystemModulesManager.java:253)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:237)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
Caused by: java.io.IOException: Cannot run program "/usr/local/bin/python3.4": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1041)
	at java.lang.Runtime.exec(Runtime.java:617)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:100)
	at org.python.pydev.runners.SimpleRunner.createProcess(SimpleRunner.java:49)
	at org.python.pydev.runners.SimpleRunner.run(SimpleRunner.java:306)
	... 9 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:135)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1022)
	... 13 more
